version: '3.1'
services:
  db_postgres:
    # We use a postgres image which version supported by PG4WP. For more detail check  https://github.com/PostgreSQL-For-Wordpress/postgresql-for-wordpress
    image: postgres:14.2
    volumes:
      - ./db_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: wordpress
      POSTGRES_PASSWORD: wordpress
      POSTGRES_DB: wordpress
    ports:
      - 5432:5432
    networks:
      - pgwpnetwork
  
  wordpress:
    build: 
      context: .   
    ports:
      - 8080:80
    restart: always
    links:
      - db_postgres
    environment:
      WORDPRESS_DB_HOST: db_postgres
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - pgwpnetwork

volumes:
  db_data:
  wordpress:
networks:
  pgwpnetwork:
    driver: bridge